"""Regenerate every committed artifact from one evaluation run.

``python -m src.report`` runs the full backtest, writes ``reports/RESULTS.md``
and re-renders the README figures. Running it is how the numbers in the repo
stay honest: they are generated, never typed.
"""

from __future__ import annotations

import argparse
from datetime import date

import pandas as pd

from .config import ROOT
from .evaluate import calibration_table
from .plots import generate_all
from .predict import N_FEATURES, run

RESULTS_MD = ROOT / "reports" / "RESULTS.md"


def _pct(x) -> str:
    return f"{100 * x:.1f}%"


def _table(df: pd.DataFrame, columns: dict[str, str]) -> str:
    """Render a frame as a GitHub markdown table, with the given headers."""
    header = "| " + " | ".join(columns.values()) + " |"
    rule = "|" + "|".join(["---"] * len(columns)) + "|"
    rows = [
        "| " + " | ".join(str(row[c]) for c in columns) + " |"
        for _, row in df.iterrows()
    ]
    return "\n".join([header, rule, *rows])


def build_markdown(results: dict) -> str:
    """Assemble the full results appendix from one run's numbers."""
    pre, post = results["pre_reconciliation"], results["post_reconciliation"]

    models = pd.DataFrame(
        [
            {"model": "Coin flip", "accuracy": _pct(0.5), "auc": "—", "brier": "—"},
            {
                "model": "Raw box score features",
                "accuracy": _pct(results["raw_features"]["accuracy"])
                if "raw_features" in results
                else "—",
                "auc": "—",
                "brier": "—",
            },
            {
                "model": "Home-court advantage only",
                "accuracy": _pct(results["home_court"]),
                "auc": "—",
                "brier": "—",
            },
        ]
        + [
            {
                "model": f"XGBoost, {label}",
                "accuracy": _pct(score["accuracy"]),
                "auc": f"{score['auc']:.3f}",
                "brier": "—",
            }
            for label, score in results.get("xgboost", {}).items()
        ]
        + [
            {
                "model": "Logistic regression (pre-reconciliation)",
                "accuracy": _pct(pre["accuracy"]),
                "auc": f"{pre['auc']:.3f}",
                "brier": f"{pre['brier']:.3f}",
            },
            {
                "model": "**Logistic regression (reconciled)**",
                "accuracy": f"**{_pct(post['accuracy'])}**",
                "auc": f"**{post['auc']:.3f}**",
                "brier": f"**{post['brier']:.3f}**",
            },
        ]
    )

    tiers = results["tiers"].copy()
    tiers["tier"] = [t.split()[0] for t in tiers["tier"]]
    tiers["definition"] = ["\\|p−0.5\\| < 0.05", "0.05 – 0.15", "≥ 0.15"]
    tiers["n_fmt"] = tiers["n"].map("{:,}".format)
    tiers["acc"] = tiers["accuracy"].map(_pct)

    seasons = results["seasons"].copy()
    seasons["n_fmt"] = seasons["n"].map("{:,}".format)
    seasons["acc"] = seasons["accuracy"].map(_pct)
    seasons["hc"] = seasons["home_court"].map(_pct)
    seasons["lift_fmt"] = seasons["lift"].map(lambda v: f"+{100 * v:.1f}")
    seasons["auc_fmt"] = seasons["auc"].map("{:.3f}".format)
    seasons["brier_fmt"] = seasons["brier"].map("{:.3f}".format)

    calib = calibration_table(results["reconciled"]).copy()
    calib["bin_fmt"] = calib["bin"].astype(str)
    calib["n_fmt"] = calib["n"].map("{:,}".format)
    calib["pred"] = calib["mean_predicted"].map("{:.3f}".format)
    calib["obs"] = calib["observed"].map("{:.3f}".format)
    calib["gap_fmt"] = calib["gap"].map("{:+.3f}".format)

    lift = f"{100 * (post['accuracy'] - pre['accuracy']):+.1f}"
    contradiction = (
        f"{_pct(results['contradiction_rate_before'])} to "
        f"{_pct(results['contradiction_rate_after'])}"
    )
    unpaired = (
        f"{results['unpaired_rows']} rows had no partner to reconcile against "
        "and were skipped."
    )
    ece = (
        f"Expected calibration error: **{results['ece_post']:.3f}** reconciled "
        f"({results['ece_pre']:.3f} before reconciliation)."
    )

    return f"""# Results

Generated by `python -m src.report` on {date.today().isoformat()}.
Every number here comes from that run — none is typed by hand.

Evaluated on **{pre['n']:,} held-out predictions** across seven seasons (2018–2024) by season-by-season walk-forward backtesting: train on every prior season, test on the next unseen one, roll forward.

---

## Model comparison

{_table(models, {"model": "Model", "accuracy": "Accuracy", "auc": "AUC", "brier": "Brier"})}

Reconciliation is worth **{lift} points** of accuracy on its own, and takes the contradiction rate from {contradiction}. {unpaired}

## Accuracy by confidence tier

{_table(tiers, {"tier": "Tier", "definition": "Definition", "n_fmt": "n", "acc": "Accuracy"})}

## Calibration

{ece}

`gap` is predicted minus observed — positive means overconfident in that bucket.
The outermost bins hold a single prediction each, so their gap is one coin
landing, not a trend.

{_table(calib, {"bin_fmt": "Predicted", "n_fmt": "n", "pred": "Mean predicted",
                "obs": "Observed", "gap_fmt": "Gap"})}

## Season by season

{_table(seasons, {"season": "Season", "n_fmt": "n", "acc": "Model",
                  "hc": "Home court", "lift_fmt": "Lift", "auc_fmt": "AUC",
                  "brier_fmt": "Brier"})}

## Selected features

Forward sequential selection over {results['n_candidates']} candidates, scored under `TimeSeriesSplit`, keeping {N_FEATURES}. Suffixes: `_x` is the team's own rolling form, `_y` the upcoming opponent's, `_opp` the opponent in the game the stat was recorded in.

{chr(10).join(f"- `{p}`" for p in results["predictors"])}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-baselines",
        action="store_true",
        help="skip the raw-feature and XGBoost comparisons (much faster)",
    )
    args = parser.parse_args()

    results = run(skip_baselines=args.skip_baselines)
    print()

    # RESULTS.md is the committed record of what this project measures. A run
    # without the baselines cannot fill in the comparison table, and a partial
    # record that overwrites a complete one is worse than no record -- so that
    # run renders the figures and leaves the document alone.
    if args.skip_baselines:
        print(
            f"Skipped {RESULTS_MD.relative_to(ROOT)}: --skip-baselines leaves the\n"
            "  model comparison incomplete. Re-run without it to refresh the report."
        )
    else:
        RESULTS_MD.parent.mkdir(parents=True, exist_ok=True)
        RESULTS_MD.write_text(build_markdown(results))
        print(f"Wrote {RESULTS_MD.relative_to(ROOT)}")

    for path in generate_all(
        results["reconciled"], results["tiers"], {"home_court": results["home_court"]}
    ):
        print(f"Wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
